apim_rg                  = "rg-apim-jmapim-dev-canadacentral-001"
apim_name                = "apim-jmapim-dev-canadacentral-001"
apim_gateway_name        = "jm-gateway-canadacentral"
apim_gateway_description = "jm-gateway2-canadaeast"
apim_gateway_region      = "alicloud-kubernetes-cluster"
# kv_name                  = "kv-jm-sre-lbuc"
# kv_rg                    = "sre-rg"