# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gke-apim-gateway-env
data:
  config.service.endpoint: "https://jm-demo-apim.management.azure-api.net/subscriptions/b79b3641-f295-4473-b807-e858d16b195b/resourceGroups/apim-rg/providers/Microsoft.ApiManagement/service/jm-demo-apim?api-version=2021-01-01-preview"
  telemetry.metrics.local: "statsd"
  telemetry.metrics.local.statsd.endpoint: "10.52.0.99:8125"
  telemetry.metrics.local.statsd.sampling: "1"
  telemetry.metrics.local.statsd.tag-format: "dogStatsD"
  telemetry.logs.std: "text"
  telemetry.logs.local.localsyslog.endpoint: "/dev/log"
  telemetry.logs.local.localsyslog.facility: "7"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-apim-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-apim-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: gke-apim-gateway
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: gke-apim-gateway
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: gke-apim-gateway-token
              key: value
        envFrom:
        - configMapRef:
            name: gke-apim-gateway-env
---
apiVersion: v1
kind: Service
metadata:
  name: gke-apim-gateway
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: gke-apim-gateway